spring:
  application:
    name: rate-limiter-service
  data:
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      routes:
        - id: dummy_api
          uri: http://httpbin.org # A safe dummy API to route to for testing
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - name: RateLimit
              args:
                capacity: 5
                refillRate: 1
                requestedTokens: 1

server:
  port: 8080
